version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            npm install
            npm run build
      - save_cache:
          paths: [node_modules]
          key: frontend-build

  scan-frontend:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Scan Frontend
          command: |
            npm install
            npm audit fix --audit-level=critical

  deploy-frontend:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip3 install awscli --upgrade
      - run:
          name: Deploying to AWS S3
          command: |
            aws s3 sync . s3://todoapplist/ --delete

workflows:
  version: 2
  build_and_scan_and_deploy:
    jobs:
      - build-frontend
      - scan-frontend:
          requires:
            - build-frontend
      - deploy-frontend:
          requires:
            - scan-frontend
